import Foundation

struct AttributeDefinition {
    let key: String
    let questionTemplates: [String]

    func generateQuestion() -> String {
        questionTemplates.randomElement() ?? questionTemplates.first ?? "¿\(key)?"
    }
}

extension AttributeDefinition {
    static let pool: [AttributeDefinition] = [
        // ── IDENTITY ──
        .init(key: "isReal", questionTemplates: [
            "¿Tu personaje es una persona real?",
            "¿Existió o existe en la vida real?",
            "¿Es un personaje de la vida real?",
            "¿Podrías encontrarlo en el mundo real?",
            "¿Está basado en alguien que realmente existe?",
        ]),
        .init(key: "isFictional", questionTemplates: [
            "¿Tu personaje es ficticio?",
            "¿Es inventado?",
            "¿Pertenece a una obra de ficción?",
            "¿Es producto de la imaginación?",
            "¿No existe en el mundo real?",
        ]),
        .init(key: "isHistorical", questionTemplates: [
            "¿Tu personaje es histórico?",
            "¿Vivió en el pasado?",
            "¿Es una figura importante de la historia?",
            "¿Aparece en los libros de historia?",
            "¿Es alguien del pasado lejano?",
        ]),
        .init(key: "isAlive", questionTemplates: [
            "¿Tu personaje está vivo actualmente?",
            "¿Sigue con vida?",
            "¿Está vivo hoy en día?",
            "¿Podrías encontrarlo vivo ahora?",
            "¿Aún no ha fallecido?",
        ]),

        // ── ORIGIN MEDIA ──
        .init(key: "isFromMovie", questionTemplates: [
            "¿Tu personaje aparece en películas?",
            "¿Lo has visto en el cine?",
            "¿Ha sido protagonista de una película?",
            "¿Ha aparecido en la pantalla grande?",
            "¿Tiene una película propia?",
        ]),
        .init(key: "isFromBook", questionTemplates: [
            "¿Tu personaje aparece en libros?",
            "¿Es de una novela o cuento?",
            "¿Lo conoces por algún libro?",
            "¿Podrías leer sobre él en una biblioteca?",
            "¿Es parte de una obra literaria?",
        ]),
        .init(key: "isFromTV", questionTemplates: [
            "¿Tu personaje aparece en televisión?",
            "¿Lo has visto en la tele?",
            "¿Es de alguna serie o programa de TV?",
            "¿Tiene un programa de televisión propio?",
            "¿Aparece en la pantalla chica?",
        ]),
        .init(key: "isFromVideoGame", questionTemplates: [
            "¿Tu personaje es de un videojuego?",
            "¿Aparece en algún videojuego?",
            "¿Es un personaje de videojuegos?",
            "¿Puedes jugar con él en un videojuego?",
            "¿Es conocido en el mundo gamer?",
        ]),
        .init(key: "isFromComic", questionTemplates: [
            "¿Tu personaje es de un cómic?",
            "¿Aparece en historietas?",
            "¿Sale en cómics o mangas?",
            "¿Tiene su propia serie de cómics?",
            "¿Lo encuentras en viñetas?",
        ]),
        .init(key: "isFromMythology", questionTemplates: [
            "¿Tu personaje es de la mitología?",
            "¿Pertenece a leyendas antiguas?",
            "¿Es parte de algún mito o leyenda?",
            "¿Proviene de creencias ancestrales?",
            "¿Es un dios o ser mitológico?",
        ]),
        .init(key: "isFromAnime", questionTemplates: [
            "¿Tu personaje es de un anime?",
            "¿Es de una serie animada japonesa?",
            "¿Aparece en algún anime?",
            "¿Es un personaje de animación japonesa?",
            "¿Tiene ojos grandes y estilo anime?",
        ]),
        .init(key: "isFromPeru", questionTemplates: [
            "¿Tu personaje es peruano?",
            "¿Nació en Perú?",
            "¿Es originario del Perú?",
            "¿Tiene raíces peruanas?",
            "¿Es conocido en el Perú?",
        ]),
        .init(key: "isFromEurope", questionTemplates: [
            "¿Tu personaje es europeo?",
            "¿Nació en Europa?",
            "¿Es de algún país de Europa?",
            "¿Tiene raíces europeas?",
            "¿Es del Viejo Continente?",
        ]),
        .init(key: "isFromAsia", questionTemplates: [
            "¿Tu personaje es asiático?",
            "¿Nació en Asia?",
            "¿Es de algún país asiático?",
            "¿Tiene raíces asiáticas?",
            "¿Es del continente asiático?",
        ]),
        .init(key: "isFromAfrica", questionTemplates: [
            "¿Tu personaje es africano?",
            "¿Nació en África?",
            "¿Es de algún país africano?",
            "¿Tiene raíces africanas?",
            "¿Es del continente africano?",
        ]),
        .init(key: "isFromNorthAmerica", questionTemplates: [
            "¿Tu personaje es norteamericano?",
            "¿Nació en Norteamérica?",
            "¿Es de EE.UU. o Canadá?",
            "¿Tiene raíces norteamericanas?",
            "¿Es del continente norteamericano?",
        ]),
        .init(key: "isLatinAmerican", questionTemplates: [
            "¿Tu personaje es latinoamericano?",
            "¿Es de algún país de Latinoamérica?",
            "¿Nació en América Latina?",
            "¿Habla español con acento latino?",
            "¿Es parte de la cultura latina?",
        ]),

        // ── FRANCHISE ──
        .init(key: "isFromMarvel", questionTemplates: [
            "¿Tu personaje es de Marvel?",
            "¿Pertenece al universo Marvel?",
            "¿Es de los cómics de Marvel?",
            "¿Aparece en el MCU?",
            "¿Stan Lee lo creó?",
        ]),
        .init(key: "isFromDC", questionTemplates: [
            "¿Tu personaje es de DC?",
            "¿Es del universo DC?",
            "¿Pertenece a DC Comics?",
            "¿Es de los mundos de DC?",
            "¿Aparece en películas de DC?",
        ]),
        .init(key: "isFromDisney", questionTemplates: [
            "¿Tu personaje es de Disney?",
            "¿Pertenece al mundo Disney?",
            "¿Es un personaje de Disney?",
            "¿Aparece en películas de Disney?",
            "¿Lo creó Walt Disney?",
        ]),
        .init(key: "isFromStarWars", questionTemplates: [
            "¿Tu personaje es de Star Wars?",
            "¿Pertenece a la saga Star Wars?",
            "¿Vive en una galaxia muy lejana?",
            "¿Usa la Fuerza?",
            "¿Es parte del universo Star Wars?",
        ]),

        // ── NATURE ──
        .init(key: "isHuman", questionTemplates: [
            "¿Tu personaje es humano?",
            "¿Es un ser humano?",
            "¿Pertenece a la raza humana?",
            "¿Es de carne y hueso como nosotros?",
            "¿No tiene poderes sobrenaturales?",
        ]),
        .init(key: "isAnimal", questionTemplates: [
            "¿Tu personaje es un animal?",
            "¿No es humano, sino animal?",
            "¿Es una criatura no humana?",
            "¿Camina en cuatro patas?",
            "¿Es una mascota o animal parlante?",
        ]),
        .init(key: "isMagical", questionTemplates: [
            "¿Tu personaje es mágico?",
            "¿Tiene habilidades mágicas?",
            "¿Usa magia o hechizos?",
            "¿Pertenece a un mundo de fantasía?",
            "¿Lo rodea un aura mágica?",
        ]),
        .init(key: "isSuperhero", questionTemplates: [
            "¿Tu personaje es un superhéroe?",
            "¿Tiene identidad secreta?",
            "¿Se dedica a salvar personas?",
            "¿Usa un traje de superhéroe?",
            "¿Lucha contra el crimen?",
        ]),
        .init(key: "isVillain", questionTemplates: [
            "¿Tu personaje es un villano?",
            "¿Es uno de los malos?",
            "¿Es un antagonista?",
            "¿Suele ser el enemigo del héroe?",
            "¿Tiene malas intenciones?",
        ]),
        .init(key: "isRoyalty", questionTemplates: [
            "¿Tu personaje es de la realeza?",
            "¿Es rey, reina o princesa?",
            "¿Pertenece a una familia real?",
            "¿Tiene un título nobiliario?",
            "¿Vive en un castillo?",
        ]),

        // ── APPEARANCE ──
        .init(key: "hasHair", questionTemplates: [
            "¿Tu personaje tiene cabello?",
            "¿Tiene pelo visible?",
            "¿Se le ve cabello?",
            "¿No es calvo?",
            "¿Tiene algún peinado distintivo?",
        ]),
        .init(key: "wearsGlasses", questionTemplates: [
            "¿Tu personaje usa gafas?",
            "¿Lleva anteojos?",
            "¿Usa lentes?",
            "¿Tiene problemas de visión?",
            "¿Usa lentes de contacto?",
        ]),
        .init(key: "hasBeard", questionTemplates: [
            "¿Tu personaje tiene barba?",
            "¿Lleva barba o bigote?",
            "¿Tiene vello facial?",
            "¿Usa barba frondosa?",
            "¿Tiene un bigote llamativo?",
        ]),
        .init(key: "isFemale", questionTemplates: [
            "¿Tu personaje es mujer?",
            "¿Es del género femenino?",
            "¿Estamos hablando de una mujer?",
            "¿Tu personaje es ella?",
            "¿Tiene apariencia femenina?",
        ]),
        .init(key: "isChild", questionTemplates: [
            "¿Tu personaje es un niño?",
            "¿Es menor de edad?",
            "¿Es un personaje infantil?",
            "¿Tiene menos de 18 años?",
            "¿Es un infante o adolescente?",
        ]),
        .init(key: "isElderly", questionTemplates: [
            "¿Tu personaje es anciano?",
            "¿Es una persona mayor?",
            "¿Tiene avanzada edad?",
            "¿Tiene el cabello canoso?",
            "¿Necesita bastón para caminar?",
        ]),

        // ── ABILITIES ──
        .init(key: "usesMagic", questionTemplates: [
            "¿Tu personaje usa magia?",
            "¿Lanza hechizos?",
            "¿Practica la brujería o hechicería?",
            "¿Estudió en una escuela de magia?",
            "¿Tiene un libro de hechizos?",
        ]),
        .init(key: "usesTechnology", questionTemplates: [
            "¿Tu personaje usa tecnología avanzada?",
            "¿Maneja dispositivos tecnológicos?",
            "¿Usa aparatos de alta tecnología?",
            "¿Es experto en gadgets?",
            "¿Usa un celular o computadora?",
        ]),
        .init(key: "hasSuperpowers", questionTemplates: [
            "¿Tu personaje tiene superpoderes?",
            "¿Posee habilidades sobrehumanas?",
            "¿Tiene poderes especiales?",
            "¿Puede hacer cosas que un humano no puede?",
            "¿Tiene un poder único?",
        ]),
        .init(key: "isStrong", questionTemplates: [
            "¿Tu personaje es físicamente fuerte?",
            "¿Tiene una fuerza fuera de lo común?",
            "¿Es conocido por su fortaleza?",
            "¿Puede levantar objetos pesados?",
            "¿Gana peleas fácilmente?",
        ]),
        .init(key: "isSmart", questionTemplates: [
            "¿Tu personaje es muy inteligente?",
            "¿Se caracteriza por su intelecto?",
            "¿Es un genio o muy astuto?",
            "¿Resuelve problemas complejos?",
            "¿Es conocido por su sabiduría?",
        ]),

        // ── ITEMS ──
        .init(key: "hasWeapon", questionTemplates: [
            "¿Tu personaje usa un arma?",
            "¿Porta algún tipo de arma?",
            "¿Utiliza armas para pelear?",
            "¿Lleva una espada o pistola?",
            "¿Tiene un arma característica?",
        ]),
        .init(key: "drivesVehicle", questionTemplates: [
            "¿Tu personaje conduce un vehículo?",
            "¿Maneja algún medio de transporte?",
            "¿Tiene un vehículo característico?",
            "¿Conduce un auto o moto?",
            "¿Pilotea una nave o avión?",
        ]),
        .init(key: "wearsCape", questionTemplates: [
            "¿Tu personaje usa capa?",
            "¿Lleva una capa puesta?",
            "¿Usa capa o manto?",
            "¿Su atuendo incluye una capa?",
            "¿Viste una capa que ondea al viento?",
        ]),
        .init(key: "wearsHat", questionTemplates: [
            "¿Tu personaje usa sombrero?",
            "¿Lleva algún tipo de gorro?",
            "¿Usa un sombrero distintivo?",
            "¿Su cabeza está cubierta?",
            "¿Tiene un tocado característico?",
        ]),

        // ── ROLE / OCCUPATION ──
        .init(key: "isAthlete", questionTemplates: [
            "¿Tu personaje es un deportista?",
            "¿Practica algún deporte?",
            "¿Es un atleta profesional?",
            "¿Juega en un equipo deportivo?",
            "¿Gana medallas o trofeos?",
        ]),
        .init(key: "isFootballer", questionTemplates: [
            "¿Tu personaje es futbolista?",
            "¿Juega fútbol profesionalmente?",
            "¿Es conocido por jugar al fútbol?",
            "¿Patea un balón por trabajo?",
            "¿Ha jugado en un equipo de fútbol?",
        ]),
        .init(key: "isGoalkeeper", questionTemplates: [
            "¿Tu personaje es portero?",
            "¿Defiende la portería?",
            "¿Usa guantes de arquero?",
            "¿Es arquero de fútbol?",
            "¿Ataja penales?",
        ]),
        .init(key: "isForward", questionTemplates: [
            "¿Tu personaje es delantero?",
            "¿Juega en la delantera?",
            "¿Su trabajo es marcar goles?",
            "¿Es un goleador?",
            "¿Ataca en su equipo?",
        ]),
        .init(key: "isMidfielder", questionTemplates: [
            "¿Tu personaje es mediocampista?",
            "¿Juega en el mediocampo?",
            "¿Distribuye el balón?",
            "¿Es volante?",
            "¿Controla el juego desde el centro?",
        ]),
        .init(key: "isDefender", questionTemplates: [
            "¿Tu personaje es defensa?",
            "¿Juega en la defensa?",
            "¿Su trabajo es evitar goles?",
            "¿Es zaguero o lateral?",
            "¿Detiene ataques rivales?",
        ]),
        .init(key: "isCaptain", questionTemplates: [
            "¿Tu personaje es capitán de su equipo?",
            "¿Lleva el brazalete de capitán?",
            "¿Es líder dentro del campo?",
            "¿Es el capitán?",
            "¿Dirige a sus compañeros?",
        ]),
        .init(key: "isLeftFooted", questionTemplates: [
            "¿Tu personaje es zurdo?",
            "¿Usa más la pierna izquierda?",
            "¿Patea con la izquierda?",
            "¿Es diestro o zurdo?",
            "¿Su pierna dominante es la izquierda?",
        ]),
        .init(key: "isTall", questionTemplates: [
            "¿Tu personaje es alto?",
            "¿Mide más de 1.80 m?",
            "¿Destaca por su estatura?",
            "¿Es una persona alta?",
            "¿Tiene gran altura?",
        ]),
        .init(key: "hasTattoos", questionTemplates: [
            "¿Tu personaje tiene tatuajes visibles?",
            "¿Está tatuado?",
            "¿Tiene tatuajes en brazos o cuerpo?",
            "¿Lleva tinta en la piel?",
            "¿Se le ven tatuajes?",
        ]),
        .init(key: "isBald", questionTemplates: [
            "¿Tu personaje es calvo?",
            "¿No tiene cabello?",
            "¿Afeita su cabeza?",
            "¿Tiene la cabeza rapada?",
            "¿Es pelado?",
        ]),

        .init(key: "isMusician", questionTemplates: [
            "¿Tu personaje es músico?",
            "¿Canta o toca un instrumento?",
            "¿Es parte de una banda musical?",
            "¿Se dedica a la música?",
            "¿Es conocido por su voz?",
        ]),
        .init(key: "isPolitician", questionTemplates: [
            "¿Tu personaje es un político?",
            "¿Gobierna o gobernó un país?",
            "¿Es presidente o ministro?",
            "¿Participa en la política?",
            "¿Tiene un cargo de gobierno?",
        ]),
        .init(key: "isWriter", questionTemplates: [
            "¿Tu personaje es escritor?",
            "¿Ha escrito libros o poemas?",
            "¿Se dedica a la literatura?",
            "¿Es autor de obras famosas?",
            "¿Ganó un premio literario?",
        ]),
        .init(key: "isScientist", questionTemplates: [
            "¿Tu personaje es científico?",
            "¿Se dedica a la ciencia?",
            "¿Hace experimentos o investiga?",
            "¿Tiene un laboratorio?",
            "¿Es inventor o investigador?",
        ]),
        .init(key: "isReligious", questionTemplates: [
            "¿Tu personaje es religioso?",
            "¿Es un líder espiritual?",
            "¿Representa a una iglesia o fe?",
            "¿Es un santo o figura religiosa?",
            "¿Predica una religión?",
        ]),

        // ── NEW ATTRIBUTES ──
        .init(key: "isFromCartoon", questionTemplates: [
            "¿Tu personaje es de una caricatura o dibujo animado?",
            "¿Aparece en dibujos animados occidentales?",
            "¿Es de un cartoon?",
            "¿Tiene estilo de animación occidental?",
            "¿Es de una serie animada no anime?",
        ]),

        .init(key: "isDancer", questionTemplates: [
            "¿Tu personaje es bailarín?",
            "¿Baila profesionalmente?",
            "¿Es conocido por sus movimientos?",
            "¿Participa en coreografías?",
            "¿Es un artista de la danza?",
        ]),
        .init(key: "isActor", questionTemplates: [
            "¿Tu personaje es actor o actriz?",
            "¿Actúa en películas o teatro?",
            "¿Es reconocido por interpretar personajes?",
            "¿Ha ganado premios de actuación?",
            "¿Es famoso por su trabajo en cine o TV?",
        ]),
        .init(key: "isSinger", questionTemplates: [
            "¿Tu personaje es cantante?",
            "¿Canta profesionalmente?",
            "¿Es conocido por su voz o música?",
            "¿Ha lanzado canciones o álbumes?",
            "¿Es un artista musical?",
        ]),
        .init(key: "isFamous", questionTemplates: [
            "¿Tu personaje es muy famoso?",
            "¿Es conocido mundialmente?",
            "¿Aparece en medios de comunicación?",
            "¿Tiene millones de seguidores?",
            "¿Es una celebridad?",
        ]),
        .init(key: "isControversial", questionTemplates: [
            "¿Tu personaje es controversial o polémico?",
            "¿Genera opiniones divididas?",
            "¿Ha estado en escándalos?",
            "¿Es amado y odiado a la vez?",
            "¿Su historia genera debate?",
        ]),
        .init(key: "isYoung", questionTemplates: [
            "¿Tu personaje es joven?",
            "¿Tiene menos de 30 años?",
            "¿Está en la flor de la vida?",
            "¿Es un adulto joven?",
            "¿No es niño ni anciano?",
        ]),

        // ── COUNTRY ──
        .init(key: "isFromBrazil", questionTemplates: [
            "¿Tu personaje es brasileño?",
            "¿Nació en Brasil?",
            "¿Es de Brasil?",
            "¿Tiene nacionalidad brasileña?",
            "¿Viene de Brasil?",
        ]),
        .init(key: "isFromArgentina", questionTemplates: [
            "¿Tu personaje es argentino?",
            "¿Nació en Argentina?",
            "¿Es de Argentina?",
            "¿Tiene nacionalidad argentina?",
            "¿Viene de Argentina?",
        ]),
        .init(key: "isFromSpain", questionTemplates: [
            "¿Tu personaje es español?",
            "¿Nació en España?",
            "¿Es de España?",
            "¿Tiene nacionalidad española?",
            "¿Viene de España?",
        ]),
        .init(key: "isFromEngland", questionTemplates: [
            "¿Tu personaje es inglés?",
            "¿Nació en Inglaterra?",
            "¿Es de Inglaterra?",
            "¿Tiene nacionalidad inglesa?",
            "¿Viene de Inglaterra?",
        ]),
        .init(key: "isFromFrance", questionTemplates: [
            "¿Tu personaje es francés?",
            "¿Nació en Francia?",
            "¿Es de Francia?",
            "¿Tiene nacionalidad francesa?",
            "¿Viene de Francia?",
        ]),
        .init(key: "isFromGermany", questionTemplates: [
            "¿Tu personaje es alemán?",
            "¿Nació en Alemania?",
            "¿Es de Alemania?",
            "¿Tiene nacionalidad alemana?",
            "¿Viene de Alemania?",
        ]),
        .init(key: "isFromItaly", questionTemplates: [
            "¿Tu personaje es italiano?",
            "¿Nació en Italia?",
            "¿Es de Italia?",
            "¿Tiene nacionalidad italiana?",
            "¿Viene de Italia?",
        ]),
        .init(key: "isFromPortugal", questionTemplates: [
            "¿Tu personaje es portugués?",
            "¿Nació en Portugal?",
            "¿Es de Portugal?",
            "¿Tiene nacionalidad portuguesa?",
            "¿Viene de Portugal?",
        ]),
        .init(key: "isFromMexico", questionTemplates: [
            "¿Tu personaje es mexicano?",
            "¿Nació en México?",
            "¿Es de México?",
            "¿Tiene nacionalidad mexicana?",
            "¿Viene de México?",
        ]),
        .init(key: "isFromColombia", questionTemplates: [
            "¿Tu personaje es colombiano?",
            "¿Nació en Colombia?",
            "¿Es de Colombia?",
            "¿Tiene nacionalidad colombiana?",
            "¿Viene de Colombia?",
        ]),
        .init(key: "isFromChile", questionTemplates: [
            "¿Tu personaje es chileno?",
            "¿Nació en Chile?",
            "¿Es de Chile?",
            "¿Tiene nacionalidad chilena?",
            "¿Viene de Chile?",
        ]),
        .init(key: "isFromUruguay", questionTemplates: [
            "¿Tu personaje es uruguayo?",
            "¿Nació en Uruguay?",
            "¿Es de Uruguay?",
            "¿Tiene nacionalidad uruguaya?",
            "¿Viene de Uruguay?",
        ]),
        .init(key: "isFromUSA", questionTemplates: [
            "¿Tu personaje es estadounidense?",
            "¿Nació en Estados Unidos?",
            "¿Es de EE.UU.?",
            "¿Tiene nacionalidad americana?",
            "¿Viene de Estados Unidos?",
        ]),
        .init(key: "isFromCanada", questionTemplates: [
            "¿Tu personaje es canadiense?",
            "¿Nació en Canadá?",
            "¿Es de Canadá?",
            "¿Tiene nacionalidad canadiense?",
            "¿Viene de Canadá?",
        ]),
        .init(key: "isFromNetherlands", questionTemplates: [
            "¿Tu personaje es neerlandés?",
            "¿Nació en Países Bajos?",
            "¿Es de Holanda?",
            "¿Tiene nacionalidad neerlandesa?",
            "¿Viene de los Países Bajos?",
        ]),
        .init(key: "isFromBelgium", questionTemplates: [
            "¿Tu personaje es belga?",
            "¿Nació en Bélgica?",
            "¿Es de Bélgica?",
            "¿Tiene nacionalidad belga?",
            "¿Viene de Bélgica?",
        ]),
        .init(key: "isFromCroatia", questionTemplates: [
            "¿Tu personaje es croata?",
            "¿Nació en Croacia?",
            "¿Es de Croacia?",
            "¿Tiene nacionalidad croata?",
            "¿Viene de Croacia?",
        ]),
        .init(key: "isFromUK", questionTemplates: [
            "¿Tu personaje es británico?",
            "¿Nació en Reino Unido?",
            "¿Es del Reino Unido?",
            "¿Tiene nacionalidad británica?",
            "¿Viene del Reino Unido?",
        ]),
        .init(key: "isFromPoland", questionTemplates: [
            "¿Tu personaje es polaco?",
            "¿Nació en Polonia?",
            "¿Es de Polonia?",
            "¿Tiene nacionalidad polaca?",
            "¿Viene de Polonia?",
        ]),
        .init(key: "isFromEgypt", questionTemplates: [
            "¿Tu personaje es egipcio?",
            "¿Nació en Egipto?",
            "¿Es de Egipto?",
            "¿Tiene nacionalidad egipcia?",
            "¿Viene de Egipto?",
        ]),
        .init(key: "isFromSweden", questionTemplates: [
            "¿Tu personaje es sueco?",
            "¿Nació en Suecia?",
            "¿Es de Suecia?",
            "¿Tiene nacionalidad sueca?",
            "¿Viene de Suecia?",
        ]),
        .init(key: "isFromJamaica", questionTemplates: [
            "¿Tu personaje es jamaicano?",
            "¿Nació en Jamaica?",
            "¿Es de Jamaica?",
            "¿Tiene nacionalidad jamaicana?",
            "¿Viene de Jamaica?",
        ]),
        .init(key: "isFromPuertoRico", questionTemplates: [
            "¿Tu personaje es puertorriqueño?",
            "¿Nació en Puerto Rico?",
            "¿Es de Puerto Rico?",
            "¿Tiene nacionalidad puertorriqueña?",
            "¿Viene de Puerto Rico?",
        ]),
        .init(key: "isFromGuatemala", questionTemplates: [
            "¿Tu personaje es guatemalteco?",
            "¿Nació en Guatemala?",
            "¿Es de Guatemala?",
            "¿Tiene nacionalidad guatemalteca?",
            "¿Viene de Guatemala?",
        ]),
        .init(key: "isFromParaguay", questionTemplates: [
            "¿Tu personaje es paraguayo?",
            "¿Nació en Paraguay?",
            "¿Es de Paraguay?",
            "¿Tiene nacionalidad paraguaya?",
            "¿Viene de Paraguay?",
        ]),
        .init(key: "isFromEcuador", questionTemplates: [
            "¿Tu personaje es ecuatoriano?",
            "¿Nació en Ecuador?",
            "¿Es de Ecuador?",
            "¿Tiene nacionalidad ecuatoriana?",
            "¿Viene de Ecuador?",
        ]),
        .init(key: "isFromVenezuela", questionTemplates: [
            "¿Tu personaje es venezolano?",
            "¿Nació en Venezuela?",
            "¿Es de Venezuela?",
            "¿Tiene nacionalidad venezolana?",
            "¿Viene de Venezuela?",
        ]),
        .init(key: "isFromBolivia", questionTemplates: [
            "¿Tu personaje es boliviano?",
            "¿Nació en Bolivia?",
            "¿Es de Bolivia?",
            "¿Tiene nacionalidad boliviana?",
            "¿Viene de Bolivia?",
        ]),
        .init(key: "isFromSouthKorea", questionTemplates: [
            "¿Tu personaje es surcoreano?",
            "¿Nació en Corea del Sur?",
            "¿Es de Corea del Sur?",
            "¿Tiene nacionalidad surcoreana?",
            "¿Viene de Corea del Sur?",
        ]),
        .init(key: "isFromJapan", questionTemplates: [
            "¿Tu personaje es japonés?",
            "¿Nació en Japón?",
            "¿Es de Japón?",
            "¿Tiene nacionalidad japonesa?",
            "¿Viene de Japón?",
        ]),
        .init(key: "isFromIndia", questionTemplates: [
            "¿Tu personaje es indio?",
            "¿Nació en India?",
            "¿Es de India?",
            "¿Tiene nacionalidad india?",
            "¿Viene de India?",
        ]),
        .init(key: "isFromSouthAfrica", questionTemplates: [
            "¿Tu personaje es sudafricano?",
            "¿Nació en Sudáfrica?",
            "¿Es de Sudáfrica?",
            "¿Tiene nacionalidad sudafricana?",
            "¿Viene de Sudáfrica?",
        ]),
        .init(key: "isFromAncientGreece", questionTemplates: [
            "¿Tu personaje es de la antigua Grecia?",
            "¿Pertenece a la mitología griega?",
            "¿Es de la Grecia clásica?",
            "¿Es un dios o héroe griego?",
            "¿Viene de la Grecia antigua?",
        ]),
        .init(key: "isFromAncientRome", questionTemplates: [
            "¿Tu personaje es de la antigua Roma?",
            "¿Pertenece a la Roma clásica?",
            "¿Es un emperador o líder romano?",
            "¿Vivió en la época del Imperio Romano?",
            "¿Viene de la Roma antigua?",
        ]),
        .init(key: "isFromAncientEgypt", questionTemplates: [
            "¿Tu personaje es del antiguo Egipto?",
            "¿Pertenece a la civilización egipcia antigua?",
            "¿Es un faraón o figura egipcia?",
            "¿Vivió en el Egipto de los faraones?",
            "¿Viene del antiguo Egipto?",
        ]),

        // ── APPEARANCE / GENRE ──
        .init(key: "isBlonde", questionTemplates: [
            "¿Tu personaje es rubio?",
            "¿Tiene el cabello rubio?",
            "¿Es de cabello claro?",
            "¿Tiene pelo rubio?",
            "¿Es conocido por ser rubio?",
        ]),
        .init(key: "isRapper", questionTemplates: [
            "¿Tu personaje es rapero?",
            "¿Canta rap?",
            "¿Es de hip-hop?",
            "¿Hace música rap?",
            "¿Es conocido por el rap?",
        ]),
        .init(key: "isRockSinger", questionTemplates: [
            "¿Tu personaje es cantante de rock?",
            "¿Canta rock?",
            "¿Es de una banda de rock?",
            "¿Hace música rock?",
            "¿Es estrella de rock?",
        ]),
        .init(key: "isPopSinger", questionTemplates: [
            "¿Tu personaje es cantante pop?",
            "¿Canta música pop?",
            "¿Es una estrella del pop?",
            "¿Hace pop?",
            "¿Es conocido por canciones pop?",
        ]),
        .init(key: "isReggaetonSinger", questionTemplates: [
            "¿Tu personaje canta reguetón?",
            "¿Es artista de reguetón?",
            "¿Hace música urbana latina?",
            "¿Es conocido por el reguetón?",
            "¿Canta reggaeton?",
        ]),
        .init(key: "isSalsaSinger", questionTemplates: [
            "¿Tu personaje canta salsa?",
            "Es artista de salsa?",
            "¿Hace música salsa?",
            "¿Es conocido por la salsa?",
            "¿Canta música tropical?",
        ]),

        // ── FOOTBALL POSITIONS ──
        .init(key: "isWinger", questionTemplates: [
            "¿Tu personaje juega como extremo?",
            "¿Es un winger?",
            "¿Juega por las bandas?",
            "¿Es extremo izquierdo o derecho?",
            "¿Juega en la banda?",
        ]),
        .init(key: "isStriker", questionTemplates: [
            "¿Tu personaje juega como delantero centro?",
            "¿Es un nueve?",
            "¿Juega de centrodelantero?",
            "¿Su posición es delantera central?",
            "¿Es un delantero de área?",
        ]),

        // ── MUSIC GENRES ──
        .init(key: "isCountrySinger", questionTemplates: [
            "¿Tu personaje canta country?",
            "¿Es cantante de música country?",
            "¿Hace country?",
            "¿Es estrella del country?",
            "¿Canta con guitarra country?",
        ]),
        .init(key: "isOperaSinger", questionTemplates: [
            "¿Tu personaje canta ópera?",
            "¿Es cantante de ópera?",
            "¿Tiene voz de ópera?",
            "¿Canta en teatros de ópera?",
            "¿Es una estrella de la ópera?",
        ]),

        // ── CAREER STAGE ──
        .init(key: "isVeteran", questionTemplates: [
            "¿Tu personaje es veterano o retirado?",
            "¿Tiene una carrera larga?",
            "¿Es de una generación anterior?",
            "¿Ya no está en su mejor momento físico?",
            "¿Es considerado una leyenda?",
        ]),

        // ── FOOTBALL ACHIEVEMENTS ──
        .init(key: "hasWonBallonDor", questionTemplates: [
            "¿Tu personaje ganó el Balón de Oro?",
            "¿Recibió el premio al mejor jugador del mundo?",
            "¿Ganó el Ballon d'Or?",
            "¿Fue elegido mejor futbolista del año?",
            "¿Tiene un Balón de Oro en su carrera?",
        ]),
        .init(key: "hasWonWorldCup", questionTemplates: [
            "¿Tu personaje ganó una Copa del Mundo?",
            "¿Fue campeón mundial con su selección?",
            "¿Levantó la Copa del Mundo?",
            "¿Ganó el Mundial de fútbol?",
            "¿Tiene una medalla de campeón mundial?",
        ]),
        .init(key: "playsInEurope", questionTemplates: [
            "¿Tu personaje juega o jugó en Europa?",
            "¿Militó en un club europeo?",
            "¿Hizo carrera en el fútbol europeo?",
            "¿Jugó en ligas europeas?",
            "¿Su carrera principal fue en Europa?",
        ]),
        .init(key: "isPlaymaker", questionTemplates: [
            "¿Tu personaje es un creador de juego?",
            "¿Es conocido por dar asistencias?",
            "¿Organiza el juego de su equipo?",
            "¿Es un mediapunta o enganche?",
            "¿Destaca por su visión de juego?",
        ]),

        // ── PERSONAL LIFE ──
        .init(key: "isMarried", questionTemplates: [
            "¿Tu personaje está casado?",
            "¿Tiene esposa o esposo?",
            "¿Contrajo matrimonio?",
            "¿Está en una relación matrimonial?",
            "¿Tiene cónyuge?",
        ]),
        .init(key: "hasChildren", questionTemplates: [
            "¿Tu personaje tiene hijos?",
            "¿Es padre o madre?",
            "¿Tiene descendencia?",
            "¿Tiene niños?",
            "¿Es progenitor?",
        ]),

        // ── ADDITIONAL COUNTRIES ──
        .init(key: "isFromNorway", questionTemplates: [
            "¿Tu personaje es noruego?",
            "¿Nació en Noruega?",
            "¿Es de Noruega?",
            "¿Tiene nacionalidad noruega?",
            "¿Viene de Noruega?",
        ]),
    ]
}
